"""add ogranizations new indentifiers

Revision ID: 103e230b8024
Revises: 18f83ebe22a4
Create Date: 2024-08-16 11:33:26.366872

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "103e230b8024"
down_revision = "18f83ebe22a4"
branch_labels = None
depends_on = None


def upgrade() -> None:
    op.execute(
        sa.schema.CreateSequence(
            sa.Sequence("nz_id_seq", start=1000, increment=1)
        )
    )
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "wis_organization",
        sa.Column(
            "nz_id",
            sa.Integer(),
            server_default=sa.text("nextval('nz_id_seq'::regclass)"),
            nullable=True,
        ),
    )
    op.add_column(
        "wis_organization", sa.Column("isics", sa.String(), nullable=True)
    )
    op.add_column(
        "wis_organization", sa.Column("duns", sa.String(), nullable=True)
    )
    op.add_column(
        "wis_organization", sa.Column("gleif", sa.String(), nullable=True)
    )
    op.add_column(
        "wis_organization", sa.Column("sing_id", sa.String(), nullable=True)
    )
    op.create_index(
        op.f("ix_wis_organization_nz_id"),
        "wis_organization",
        ["nz_id"],
        unique=True,
    )
    op.create_unique_constraint(None, "wis_organization", ["isics"])
    op.create_unique_constraint(None, "wis_organization", ["sing_id"])
    op.create_unique_constraint(None, "wis_organization", ["duns"])
    op.create_unique_constraint(None, "wis_organization", ["gleif"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_wis_organization_nz_id"), table_name="wis_organization"
    )
    op.drop_column("wis_organization", "sing_id")
    op.drop_column("wis_organization", "gleif")
    op.drop_column("wis_organization", "duns")
    op.drop_column("wis_organization", "isics")
    op.drop_column("wis_organization", "nz_id")

    op.execute(sa.schema.DropSequence(sa.Sequence("nz_id_seq")))
    # ### end Alembic commands ###
