"""Ref ids for restatement model

Revision ID: 69110fe2c07e
Revises: 882b29945924
Create Date: 2024-09-11 22:19:45.079624

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "69110fe2c07e"
down_revision = "882b29945924"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "wis_restatement",
        sa.Column("root_obj_id", sa.Integer(), nullable=False),
    )
    op.add_column(
        "wis_restatement",
        sa.Column("active_obj_id", sa.Integer(), nullable=False),
    )
    op.add_column(
        "wis_restatement",
        sa.Column("history_prev_id", sa.Integer(), nullable=True),
    )
    op.add_column(
        "wis_restatement",
        sa.Column("history_next_id", sa.Integer(), nullable=True),
    )

    # Rename obj_id to target_obj_id
    op.alter_column(
        "wis_restatement", "obj_id", new_column_name="target_obj_id"
    )

    op.create_foreign_key(
        "wis_restatement_root_obj_id_fkey",
        "wis_restatement",
        "wis_obj",
        ["root_obj_id"],
        ["id"],
    )
    op.create_foreign_key(
        "wis_restatement_active_obj_id_fkey",
        "wis_restatement",
        "wis_obj",
        ["active_obj_id"],
        ["id"],
    )
    op.create_foreign_key(
        "wis_restatement_history_prev_id_fkey",
        "wis_restatement",
        "wis_restatement",
        ["history_prev_id"],
        ["id"],
    )
    op.create_foreign_key(
        "wis_restatement_history_next_id_fkey",
        "wis_restatement",
        "wis_restatement",
        ["history_next_id"],
        ["id"],
    )


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "wis_restatement_history_next_id_fkey",
        "wis_restatement",
        type_="foreignkey",
    )
    op.drop_constraint(
        "wis_restatement_history_prev_id_fkey",
        "wis_restatement",
        type_="foreignkey",
    )
    op.drop_constraint(
        "wis_restatement_active_obj_id_fkey",
        "wis_restatement",
        type_="foreignkey",
    )
    op.drop_constraint(
        "wis_restatement_root_obj_id_fkey",
        "wis_restatement",
        type_="foreignkey",
    )

    # Rename target_obj_id back to obj_id
    op.alter_column(
        "wis_restatement", "target_obj_id", new_column_name="obj_id"
    )

    op.drop_column("wis_restatement", "history_next_id")
    op.drop_column("wis_restatement", "history_prev_id")
    op.drop_column("wis_restatement", "active_obj_id")
    op.drop_column("wis_restatement", "root_obj_id")
