"""Update restatements data source

Revision ID: 7612878fc19d
Revises: d2540c763e54
Create Date: 2024-11-11 12:58:36.186218

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "7612878fc19d"
down_revision = "d2540c763e54"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "wis_restatement",
        "data_source",
        existing_type=sa.INTEGER(),
        type_=sa.String(),
        existing_nullable=True,
    )
    op.drop_index("wis_restatement_obj_id_idx", table_name="wis_restatement")
    op.create_index(
        "wis_restatement_active_obj_id_idx",
        "wis_restatement",
        ["active_obj_id"],
        unique=False,
    )
    op.create_index(
        "wis_restatement_root_obj_id_idx",
        "wis_restatement",
        ["root_obj_id"],
        unique=False,
    )
    op.create_index(
        "wis_restatement_target_obj_id_idx",
        "wis_restatement",
        ["target_obj_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "wis_restatement_target_obj_id_idx", table_name="wis_restatement"
    )
    op.drop_index(
        "wis_restatement_root_obj_id_idx", table_name="wis_restatement"
    )
    op.drop_index(
        "wis_restatement_active_obj_id_idx", table_name="wis_restatement"
    )
    op.create_index(
        "wis_restatement_obj_id_idx",
        "wis_restatement",
        ["target_obj_id"],
        unique=False,
    )
    op.alter_column(
        "wis_restatement",
        "data_source",
        existing_type=sa.String(),
        type_=sa.INTEGER(),
        existing_nullable=True,
    )
    # ### end Alembic commands ###
