"""added tracking table

Revision ID: 820a33a33166
Revises: 9414cf243f42
Create Date: 2024-09-03 16:26:05.964554

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "820a33a33166"
down_revision = "9414cf243f42"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "wis_tracking",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_email", sa.String(), nullable=False),
        sa.Column("api_endpoint", sa.String(), nullable=False),
        sa.Column("date_time", sa.DateTime(), nullable=False),
        sa.Column(
            "source",
            sa.Enum("WEB", "SCRIPT", name="sourceenum"),
            nullable=False,
        ),
        sa.Column("result", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("wis_tracking_user_id_idx", table_name="wis_tracking")
    op.drop_table("wis_tracking")
    # ### end Alembic commands ###
