"""restatement simplification

Revision ID: 83acb4a0009c
Revises: 7612878fc19d
Create Date: 2024-11-23 21:43:35.918616

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "83acb4a0009c"
down_revision = "7612878fc19d"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "wis_restatement", sa.Column("obj_id", sa.Integer(), nullable=False)
    )
    op.add_column(
        "wis_restatement", sa.Column("group_id", sa.Integer(), nullable=False)
    )
    op.drop_index(
        "wis_restatement_active_obj_id_idx", table_name="wis_restatement"
    )
    op.drop_index(
        "wis_restatement_root_obj_id_idx", table_name="wis_restatement"
    )
    op.drop_index(
        "wis_restatement_target_obj_id_idx", table_name="wis_restatement"
    )
    op.create_index(
        "wis_restatement_group_id_idx",
        "wis_restatement",
        ["group_id"],
        unique=False,
    )
    op.create_index(
        "wis_restatement_obj_id_idx",
        "wis_restatement",
        ["obj_id"],
        unique=False,
    )
    op.drop_constraint(
        "wis_restatement_obj_id_fkey", "wis_restatement", type_="foreignkey"
    )
    op.drop_constraint(
        "wis_restatement_active_obj_id_fkey",
        "wis_restatement",
        type_="foreignkey",
    )
    op.drop_constraint(
        "wis_restatement_root_obj_id_fkey",
        "wis_restatement",
        type_="foreignkey",
    )
    op.drop_constraint(
        "wis_restatement_history_prev_id_fkey",
        "wis_restatement",
        type_="foreignkey",
    )
    op.drop_constraint(
        "wis_restatement_history_next_id_fkey",
        "wis_restatement",
        type_="foreignkey",
    )
    op.create_foreign_key(
        None, "wis_restatement", "wis_obj", ["obj_id"], ["id"]
    )
    op.create_foreign_key(
        None, "wis_restatement", "wis_obj", ["group_id"], ["id"]
    )
    op.drop_column("wis_restatement", "root_obj_id")
    op.drop_column("wis_restatement", "history_prev_id")
    op.drop_column("wis_restatement", "history_next_id")
    op.drop_column("wis_restatement", "active_obj_id")
    op.drop_column("wis_restatement", "target_obj_id")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "wis_restatement",
        sa.Column(
            "target_obj_id", sa.INTEGER(), autoincrement=False, nullable=False
        ),
    )
    op.add_column(
        "wis_restatement",
        sa.Column(
            "active_obj_id", sa.INTEGER(), autoincrement=False, nullable=False
        ),
    )
    op.add_column(
        "wis_restatement",
        sa.Column(
            "history_next_id", sa.INTEGER(), autoincrement=False, nullable=True
        ),
    )
    op.add_column(
        "wis_restatement",
        sa.Column(
            "history_prev_id", sa.INTEGER(), autoincrement=False, nullable=True
        ),
    )
    op.add_column(
        "wis_restatement",
        sa.Column(
            "root_obj_id", sa.INTEGER(), autoincrement=False, nullable=False
        ),
    )
    op.drop_constraint(None, "wis_restatement", type_="foreignkey")
    op.drop_constraint(None, "wis_restatement", type_="foreignkey")
    op.create_foreign_key(
        "wis_restatement_history_next_id_fkey",
        "wis_restatement",
        "wis_restatement",
        ["history_next_id"],
        ["id"],
    )
    op.create_foreign_key(
        "wis_restatement_history_prev_id_fkey",
        "wis_restatement",
        "wis_restatement",
        ["history_prev_id"],
        ["id"],
    )
    op.create_foreign_key(
        "wis_restatement_root_obj_id_fkey",
        "wis_restatement",
        "wis_obj",
        ["root_obj_id"],
        ["id"],
    )
    op.create_foreign_key(
        "wis_restatement_active_obj_id_fkey",
        "wis_restatement",
        "wis_obj",
        ["active_obj_id"],
        ["id"],
    )
    op.create_foreign_key(
        "wis_restatement_obj_id_fkey",
        "wis_restatement",
        "wis_obj",
        ["target_obj_id"],
        ["id"],
    )
    op.drop_index("wis_restatement_obj_id_idx", table_name="wis_restatement")
    op.drop_index("wis_restatement_group_id_idx", table_name="wis_restatement")
    op.create_index(
        "wis_restatement_target_obj_id_idx",
        "wis_restatement",
        ["target_obj_id"],
        unique=False,
    )
    op.create_index(
        "wis_restatement_root_obj_id_idx",
        "wis_restatement",
        ["root_obj_id"],
        unique=False,
    )
    op.create_index(
        "wis_restatement_active_obj_id_idx",
        "wis_restatement",
        ["active_obj_id"],
        unique=False,
    )
    op.drop_column("wis_restatement", "group_id")
    op.drop_column("wis_restatement", "obj_id")
    # ### end Alembic commands ###
