"""added organization alias table

Revision ID: 882b29945924
Revises: 9602b11e94f6
Create Date: 2024-09-06 14:08:33.335752

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "882b29945924"
down_revision = "9602b11e94f6"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "wis_organization_alias",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("legal_name", sa.String(), nullable=False),
        sa.Column("alias", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_wis_organization_alias_legal_name"),
        "wis_organization_alias",
        ["legal_name"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_wis_organization_alias_legal_name"),
        table_name="wis_organization_alias",
    )
    op.drop_table("wis_organization_alias")
    # ### end Alembic commands ###
