"""add nz_id as foreign key in organization alias

Revision ID: 8eb21eeeb2a2
Revises: ecbda1c18504
Create Date: 2024-09-10 14:12:43.829118

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "8eb21eeeb2a2"
down_revision = "ecbda1c18504"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "wis_organization_alias",
        sa.Column("nz_id", sa.Integer(), nullable=True),
    )
    op.drop_index(
        "ix_wis_organization_alias_legal_name",
        table_name="wis_organization_alias",
    )
    op.create_foreign_key(
        None,
        "wis_organization_alias",
        "wis_organization",
        ["nz_id"],
        ["nz_id"],
    )
    op.drop_column("wis_organization_alias", "legal_name")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "wis_organization_alias",
        sa.Column(
            "legal_name", sa.VARCHAR(), autoincrement=False, nullable=False
        ),
    )
    op.drop_constraint(None, "wis_organization_alias", type_="foreignkey")
    op.create_index(
        "ix_wis_organization_alias_legal_name",
        "wis_organization_alias",
        ["legal_name"],
        unique=False,
    )
    op.drop_column("wis_organization_alias", "nz_id")
    # ### end Alembic commands ###
