"""Add wis_data_model table

Revision ID: ec884e2525db
Revises: 3ff54765b421
Create Date: 2024-10-08 13:46:19.784278

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "ec884e2525db"
down_revision = "8eb21eeeb2a2"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "wis_data_model",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("table_view_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["table_view_id"], ["wis_table_view.id"], ondelete="SET NULL"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_wis_data_model_id"), "wis_data_model", ["id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_wis_data_model_id"), table_name="wis_data_model")
    op.drop_table("wis_data_model")
    # ### end Alembic commands ###
