"""improve aggregated object view model

Revision ID: ecbda1c18504
Revises: 882b29945924
Create Date: 2024-09-10 09:35:17.174377

"""

from datetime import datetime

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "ecbda1c18504"
down_revision = "69110fe2c07e"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "wis_aggregated_obj_view",
        sa.Column(
            "created_on",
            sa.DateTime(),
            nullable=False,
            server_default=str(datetime.now()),
        ),
    )
    op.drop_constraint(
        "wis_aggregated_obj_view_table_def_id_fkey",
        "wis_aggregated_obj_view",
        type_="foreignkey",
    )
    op.drop_column("wis_aggregated_obj_view", "table_def_id")
    op.alter_column(
        "wis_obj", "nz_id", existing_type=sa.INTEGER(), nullable=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "wis_obj", "nz_id", existing_type=sa.INTEGER(), nullable=True
    )
    op.add_column(
        "wis_aggregated_obj_view",
        sa.Column(
            "table_def_id", sa.INTEGER(), autoincrement=False, nullable=False
        ),
    )
    op.create_foreign_key(
        "wis_aggregated_obj_view_table_def_id_fkey",
        "wis_aggregated_obj_view",
        "wis_table_def",
        ["table_def_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.drop_column("wis_aggregated_obj_view", "created_on")
    # ### end Alembic commands ###
