"""Make lei optional in wis_obj

Revision ID: fa3f0bdbdd1f
Revises: 83acb4a0009c
Create Date: 2024-11-28 15:11:05.626271

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "fa3f0bdbdd1f"
down_revision = "83acb4a0009c"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "wis_obj", "lei", existing_type=sa.VARCHAR(length=32), nullable=True
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "wis_obj", "lei", existing_type=sa.VARCHAR(length=32), nullable=False
    )
    # ### end Alembic commands ###
