#!/bin/sh
set -e

psql -v ON_ERROR_STOP=1 --host "$POSTGRES_HOST" --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
	    CREATE USER $DB__MAIN__USER WITH ENCRYPTED PASSWORD '$DB__MAIN__PASSWORD';
	    GRANT ALL PRIVILEGES ON DATABASE $DB__MAIN__DATABASE TO $DB__MAIN__USER;
	    ALTER DATABASE $DB__MAIN__DATABASE OWNER TO $DB__MAIN__USER;
	    GRANT ALL ON SCHEMA public TO $DB__MAIN__USER;
EOSQL
